// <auto-generated />
using BibliotecaCatalogo.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BibliotecaCatalogo.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260925003340_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BibliotecaCatalogo.Domain.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Authors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Gabriel García Márquez"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "J.R.R. Tolkien"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Robert C. Martin"
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Yuval Noah Harari"
                        });
                });

            modelBuilder.Entity("BibliotecaCatalogo.Domain.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Isbn")
                        .IsUnique();

                    b.ToTable("Books", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            CategoryId = 1,
                            Isbn = "978-0307474728",
                            PublicationYear = 1967,
                            Title = "Cien años de soledad"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            CategoryId = 1,
                            Isbn = "978-0307389732",
                            PublicationYear = 1985,
                            Title = "El amor en los tiempos del cólera"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            CategoryId = 2,
                            Isbn = "978-0261102217",
                            PublicationYear = 1937,
                            Title = "El Hobbit"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 2,
                            CategoryId = 2,
                            Isbn = "978-0618640157",
                            PublicationYear = 1954,
                            Title = "El Señor de los Anillos"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 3,
                            CategoryId = 3,
                            Isbn = "978-0132350884",
                            PublicationYear = 2008,
                            Title = "Clean Code"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 3,
                            CategoryId = 3,
                            Isbn = "978-0134494166",
                            PublicationYear = 2017,
                            Title = "Clean Architecture"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 4,
                            CategoryId = 4,
                            Isbn = "978-0062316097",
                            PublicationYear = 2011,
                            Title = "Sapiens: De animales a dioses"
                        });
                });

            modelBuilder.Entity("BibliotecaCatalogo.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Novela"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fantasía"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ingeniería de Software"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Historia"
                        });
                });

            modelBuilder.Entity("BibliotecaCatalogo.Domain.Entities.Book", b =>
                {
                    b.HasOne("BibliotecaCatalogo.Domain.Entities.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BibliotecaCatalogo.Domain.Entities.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BibliotecaCatalogo.Domain.Entities.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("BibliotecaCatalogo.Domain.Entities.Category", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
